%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-rosbag-editor
Version:        0.4.2
Release:        1%{?dist}
Summary:        ROS rosbag_editor package

License:        MIT
URL:            http://wiki.ros.org/rosbag_editor
Source0:        %{name}-%{version}.tar.gz

Requires:       qt5-qtbase-devel
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-rosbag-storage
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-tf
Requires:       ros-melodic-tf2-msgs
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rosbag
BuildRequires:  ros-melodic-rosbag-storage
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tf2-msgs

%description
The rosbag_editor package

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Sat Oct 26 2019 dfaconti <davide.faconti@gmail.com> - 0.4.2-1
- Autogenerated by Bloom

* Fri Oct 25 2019 dfaconti <davide.faconti@gmail.com> - 0.4.1-1
- Autogenerated by Bloom

* Tue Oct 15 2019 dfaconti <davide.faconti@gmail.com> - 0.3.0-1
- Autogenerated by Bloom

